version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - ps: Install-Product node 6 x64
  - set CI=true
  - git reset --hard HEAD
  - npm install npm -g
  - npm install grunt-cli -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run test

before_deploy:
  - grunt dist
  - npm run deploy-appveyor

deploy:
  release: Space Invader-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: MlfKyZtLHvTys776AZ3o3btQQTtEUH2ePWSH98OX39TY/q6NBeoSAUkvbDkawB2ramHtLmuMj2dNE0hcSg2Fmo+vrQu1NQ6iUQeZPClzainwlAH3bmeBqDJFKyFK0vxXVWceiLLQo5QgUtfb+xsRbxQHXkFeg4Rllxj6pr001S+qhI08oz9gtRTeBBLyOuinSC5y2lpfLyxbB+Ym13Or5ngDhuASH8jQS+wRjWs1/LOkldVANK3qx4RQVhbEJYkA121FTHsG77hWNpTc7TXu4iFCPRVUq+eyl2rB/+vZDQpcA8sew5NdAbG/ovSm/5nDnZti+7pxBC12ykwA5WPS51GxOOFk36AmvdV/PPHRcFxf1cy6OrrrnmLAkn2EEdHCKvPrJGLGr2B7wihiH/B4nJBBd/KMsg/UkfSmtkXDKR9SywRqKKxg2u56d1pvQlVh1wV56iHwUi5nZnMrEOsGkZjVzEcUuShNg2Z1TD2fuYxREM+8YrtzIbIPonXyj7mk6zsxTEansMjOS1SZpqOnGiNARaMcOx/J4QYSMB0e3Z0cmvvnTcm0K4/ad/2VqAXhNK7u/CQGBiqpjSAnv+hGZHXxgpCQkaygQalrPTWoP9pNIoKWAloOBtHC6uxu3DZPNv6txECbH+Ky3GwPlrRiI2nyQicUP6yGzg8cUh7lczM=
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

test: off
